### ISSUE TITLE
possible additional internal validation for sets of codes

### ISSUE THREAD

**Issue by jackwasey** [jackwasey/icd9#40]
There is an implication that some codes are mutually exclusive. E.g.
http://www.icd9data.com/2012/Volume1/390-459/430-438/436/436.htm

**Comment by StephenSinger** [comment]
Unfortunately the "excludes notes" are far from unambiguous and encompass
situations in which the "excluded" code must, may, and must not be used!
From the official guidelines:

" Excludes: An excludes note under a code indicates that the terms excluded
from the code are to be coded elsewhere. In some cases the codes for the
excluded terms should not be used in conjunction with the code from which
it is excluded. An example of this is a congenital condition excluded from
an acquired form of the same condition. The congenital and acquired codes
should not be used together. In other cases, the excluded terms may be used
together with an excluded code. An example of this is when fractures of
different bones are coded to different codes. Both codes may be used
together if both types of fractures are present."

**Comment by jackwasey** [comment]
Thanks for the comment. I guess it was a long shot. Even if there were clear contradictions, it would seem unlikely that this would contribute much in bulk data analysis, beyond possibly excluding a very small number of cases. Therefore closing this issue.
