### ISSUE TITLE
Quan version of Charlson score

### ISSUE THREAD

**Issue by jackwasey** [jackwasey/icd9#64]
Most people use the original scores, but Quan offers a slightly different arrangement, possibly with better predictive power with more recent validation.

**Comment by wmurphyrd** [comment]
I could definitely do this one, but I searched before to find Quan's alternate scores after seeing your comment in the function documentation and couldn't find them. Do you have the reference handy?

**Comment by jackwasey** [comment]
Thanks very much, that would be great.

1.Quan, H. et al. Updating and Validating the Charlson Comorbidity Index and Score for Risk Adjustment in Hospital Discharge Abstracts Using Data From 6 Countries. Am. J. Epidemiol. 173, 676–682 (2011).

**Comment by jackwasey** [comment]
fixed by 8dd727d with many thanks to @wmurphyrd
