### ISSUE TITLE
Procedure Codes

### ISSUE THREAD

**Issue by finkelm** [jackwasey/icd9#78]
It seems only diagnosis codes are available in this package. It may benefit from inclusion of procedure codes as well (https://en.wikipedia.org/wiki/ICD-9-CM_Volume_3).

**Comment by anobel** [comment]
I think this duplicates an open issue #11 . on the someday maybe list

**Comment by jackwasey** [comment]
Thanks for adding the issue. I agree it is a duplicate, and that it would be important to add. I personally don't have any need for this now, but I'd welcome contributions. The framework is all there for adding a new code type. Would you be interested?
